"""add name column

Revision ID: bdc6e0586c71
Revises: dc9d76d4ed29
Create Date: 2025-05-09 18:57:51.021726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdc6e0586c71"
down_revision: Union[str, None] = "dc9d76d4ed29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "fight_participants",
        sa.Column("name", sa.Text(), nullable=False, server_default=""),
    )

    # remove the default so new inserts must specify it
    op.alter_column("fight_participants", "name", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fight_participants", "name")
    # ### end Alembic commands ###
