# deploy/docker-compose.yml
services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    working_dir: /app
    command: >
      uvicorn
      --workers 4
      --proxy-headers
      --host 0.0.0.0
      --port 8010
      daoc_scraper.api:app
    restart: always
    ports:
      - '8010:8010'
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env:ro
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/fights.db
      - PYTHONUNBUFFERED=1
    networks:
      - api_net
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    networks:
      - api_net
      - selenium_net
  scheduler:
    build:
      context: ..                
      dockerfile: deploy/Dockerfile
    working_dir: /app
    command: python -m daoc_scraper.scheduler
    depends_on:
      - api
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=1
      - SELENIUM_URL=http://selenium-hub:4444
    networks:
      - selenium_net

networks:
  selenium_net:
    external: true
  api_net:
    external: false
