# deploy/docker-compose.yml
version: '3.8'
services:
  api:
    build:
      context: ..               
      dockerfile: deploy/Dockerfile
    working_dir: /app
    command: uvicorn daoc_scraper.api:app --host 0.0.0.0 --port 8010
    network_mode: host
    ports:
      - '8010:8010'
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env:ro
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/fights.db

  scheduler:
    build:
      context: ..                
      dockerfile: deploy/Dockerfile
    working_dir: /app
    command: python daoc_scraper/scheduler.py
    network_mode: host
    depends_on:
      - api
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env:ro
    restart: always
