# deploy/docker-compose.yml
services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    working_dir: /app
    command: uvicorn daoc_scraper.api:app --host 0.0.0.0 --port 8010
    ports:
      - '8010:8010'
    volumes:
      - ../data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/fights.db
      - PYTHONUNBUFFERED=1
  scheduler:
    build:
      context: ..                
      dockerfile: deploy/Dockerfile
    working_dir: /app
    command: python daoc_scraper/scheduler.py
    depends_on:
      - api
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=1
      - HEADLESS=true
      - SELENIUM_URL=http://selenium:4444
    networks:
      - selenium_net
networks:
  selenium_net:
    external: true
